apiVersion: v1
entries:
  k8sforjava:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-29T18:23:02.695528007+01:00"
    description: A Helm chart for deploying the K8sForJava application
    digest: 36557c05d1ae3a3c8f6ccadf0c83c9bd4e981fb94e0203d911c6b620192338a3
    name: k8sforjava
    type: application
    urls:
    - https://vincentgwzhang.github.io/K8sForJava/k8sforjava-0.1.0.tgz
    version: 0.1.0
generated: "2024-12-29T18:23:02.69527622+01:00"
